### ISSUE TITLE
TypeError: a.getTime is not a function

### ISSUE THREAD

**Issue by juiwen** [bunkat/later#175]
i use later and show error message:

error: TypeError: a.getTime is not a function
error:     at /usr/local/lib/node_modules/later/later.js:778:34
error:     at findNext (/usr/local/lib/node_modules/later/later.js:787:23)
error:     at getInstances (/usr/local/lib/node_modules/later/later.js:637:52)
error:     at Object.next (/usr/local/lib/node_modules/later/later.js:798:16)
error:     at scheduleTimeout (/usr/local/lib/node_modules/later/later.js:817:38)
error:     at Object.later.setTimeout (/usr/local/lib/node_modules/later/later.js:814:7)
error:     at Object.later.setInterval (/usr/local/lib/node_modules/later/later.js:845:19)
error:     at run_schedule (/Data/Git/ipac/node/modules/schedule.js:76:33)
error:     at Object.exports.register (/Data/Git/ipac/node/modules/schedule.js:103:5)
error:     at Object.exports.register (/Users/juiwen/test/flows/flow10.js:31:12)

if a value is zero and the error happen

**Comment by RocheVal** [comment]
Did someone find any workaround ?
